### ISSUE TITLE
`cargo test` throw `undefined reference to 'napi_create_object'` on Linux CI

### ISSUE THREAD

**Issue by wre232114** [napi-rs/napi-rs#1099]
When running `cargo test` on CI(Linux), following error occurs:

```
error: linking with `cc` failed: exit status: 1
= note: "cc" "-m64"  ....

...

...: undefined reference to `napi_create_object'
```

The same `cargo test` works fine on MacOS

**Comment by messense** [comment]
@chenjun1011 Have you tried install Nodejs before running `cargo test`?

```yaml
- uses: actions/setup-node@v3
```

**Comment by chenjun1011** [comment]
Still have the same problem, after setup node.

https://github.com/ice-lab/swc/runs/6877711481?check_suite_focus=true

**Comment by messense** [comment]
I think the problem is that Nodejs does not provide a shared library (libnode.so) but only a `node` executable. And N-API extensions built with napi-rs cli are compiled to shared library which allows undefined external symbols on Linux, but `cargo test` builds executables so it needs a Nodejs shared library to find theses external symbols.

Unfortunately [there isn't a embedding API for N-API right now](https://github.com/nodejs/node/issues/23265), so I think the easiest way forward is making `napi` an on-by-default optional feature and feature-gate related code then run `cargo test --no-default-features` instead.

**Cargo.toml**:
```
[features]
default = ["napi"]
```

Or you can split your project into two crates, a Nodejs independent crate and a N-API extension crate.

**Comment by Brooooooklyn** [comment]
Fixed on https://github.com/ice-lab/swc/pull/24 , /cc @wre232114

**Comment by chenjun1011** [comment]
@Brooooooklyn Thank you for your PR, it's ok now  https://github.com/ice-lab/swc/runs/6891561403?check_suite_focus=true

**Comment by outkine** [comment]
@messense Thank you for sharing that solution! It fixes the problem on Linux, but I'm still getting "undefined reference" errors on MacOS. Do you have any idea if that might be because MacOS doesn't allow undefined external symbols, and if there's any way to get around that problem?
