### ISSUE TITLE
Rust 1.81.0 breaks zig cross compile aarch64-apple-darwin on linux

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#2249]
`note: error: unsupported linker arg: -exported_symbols_list`

https://github.com/napi-rs/napi-rs/actions/runs/10833496954/job/30060429790?pr=2248

**Comment by messense** [comment]
See https://github.com/rust-cross/cargo-zigbuild/issues/164#issuecomment-1712791164

**Comment by messense** [comment]
Should've been fixed by https://github.com/rust-cross/cargo-zigbuild/pull/273 which will be released in next version.

**Comment by messense** [comment]
The fix was released in cargo-zigbuild [0.19.2](https://github.com/rust-cross/cargo-zigbuild/releases/tag/v0.19.2).

**Comment by Brooooooklyn** [comment]
@messense still failed: https://github.com/napi-rs/cross-build/actions/runs/10864153611/job/30438172738

**Comment by lianghx-319** [comment]
If fixed please notice me? I am suffering this too.

**Comment by anttiharju** [comment]
zig 0.16 supports -exported_symbols_list
