### ISSUE TITLE
The trait `NapiRaw` is not implemented error when returning an other class

### ISSUE THREAD

**Issue by Tpt** [napi-rs/napi-rs#933]
First, thank you so much for napi-rs 2.0. It looks amazing.
And sorry for bothering you with an error.

Sadly I tried the following code:
```rust
use napi_derive::napi;

#[napi]
pub struct Sound {}

#[napi]
pub struct Cat {}

#[napi]
impl Cat {
    #[napi]
    pub fn meow(&self) -> Sound {
        Sound {}
    }
}
```

And got the following compile error:
```
error[E0277]: the trait bound `Sound: NapiRaw` is not satisfied
  --> nodejs/src/lib.rs:9:1
   |
9  | #[napi]
   | ^^^^^^^ the trait `NapiRaw` is not implemented for `Sound`
   |
   = note: required because of the requirements on the impl of `ToNapiValue` for `Sound`
note: required by `to_napi_value`
  --> cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.0.0/src/bindgen_runtime/js_values.rs:56:3
   |
56 |   unsafe fn to_napi_value(env: sys::napi_env, val: Self) -> Result<sys::napi_value>;
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the attribute macro `napi` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `thecate` due to previous error
```

Am I doing something wrong with the placement of the `napi` macro call?

**Comment by shinotheshino** [comment]
+1 -- I am also having this issue. Is this a bad assumption about how classes are intended to work with Napi 2?

**Comment by Brooooooklyn** [comment]
@Tpt `Sound` is not implemented `NapiRaw` because it is lacking of `constructor`.

After https://github.com/napi-rs/napi-rs/pull/964 you can write codes like this:


```rust
use napi_derive::napi;

#[nap(constructor)i]
pub struct Sound {}

#[napi]
pub struct Cat {}

#[napi]
impl Cat {
    #[napi]
    pub fn meow(&self) -> Sound {
        Sound {}
    }
}
```

**Comment by mischnic** [comment]
> Sound is not implemented NapiRaw because it is lacking of constructor.

That solution doesn't work if `Sound` contains fields that shouldn't or cannot be exposed to JS.

**Comment by Brooooooklyn** [comment]
@mischnic  Then ou can define `#[constructor]` in `impl` block:

```rust
#[napi]
struct Sound {
  inner: InnerSound
}

#[napi]
impl Sound {
  #[napi(constructor)]
  pub new() -> Self {
    Self { inner: InnderSound::new() }
  }
}

```

Anyway, you need `constructor` on your struct, or the NAPI-RS don't know how to create JavaScript instance from it.

**Comment by mischnic** [comment]
I still get this error with the constructor method

```
the trait bound `Sound: napi::NapiRaw` is not satisfied
required because of the requirements on the impl of `napi::bindgen_prelude::ToNapiValue` for `Sound`
````

```rust
#[napi]
pub struct Cat {}
#[napi]
impl Cat {
  #[napi(constructor)]
  pub fn new() -> Self {
    Self {
    }
  }

  #[napi]
  pub fn meow(&self) -> Sound {
    Sound::new()
  }
}

struct InnerSound {}
impl InnerSound {
  pub fn new() -> Self {
    Self {}
  }
}

#[napi]
struct Sound {
  inner: InnerSound,
}

#[napi]
impl Sound {
  #[napi(constructor)]
  pub fn new() -> Self {
    Self {
      inner: InnerSound::new(),
    }
  }
}
```

> Anyway, you need constructor on your struct, or the NAPI-RS don't know how to create JavaScript instance from it.

You mean what I'm trying to do is impossible?

```rust
#[napi]
pub struct Cat {
  inner: Rc<RefCell<Vec<u8>>>,
}

#[napi]
impl Cat {
  #[napi(constructor)]
  pub fn new(inner: Rc<RefCell<Vec<u8>>>) -> Self {
    Self {
      inner: Rc::new(RefCell::new(Vec::new())),
    }
  }

  #[napi]
  pub fn meow(&self) -> Sound {
    Sound {
      inner: Rc::clone(&self.inner),
    }
  }
}

#[napi]
struct Sound {
  inner: Rc<RefCell<Vec<u8>>>,
}

#[napi]
impl Sound {
  #[napi(constructor)]
  pub fn new(inner: Rc<RefCell<Vec<u8>>>) -> Self {
    Self { inner }
  }
}
```

**Comment by Brooooooklyn** [comment]
@mischnic Fixed in `napi-derive@2.0.3`

**Comment by mischnic** [comment]
Thank for the quick response, but I'm still getting an error

```js
let x = new mod.Cat();
let y = x.meow();
console.log(y.get())
              ^
Error: Failed to unwrap shared reference of `Sound` type from napi value
```

```rust
#[napi]
pub struct Cat {}

#[napi]
impl Cat {
  #[napi(constructor)]
  pub fn new() -> Self {
    Self {}
  }

  #[napi]
  pub fn meow(&self) -> Sound {
    Sound::new()
  }
}

#[napi]
struct Sound {}

#[napi]
impl Sound {
  pub fn new() -> Self {
    Self {}
  }

  #[napi]
  pub fn get(&self) -> u32 {
    1234
  }
}
```
